// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXvQFPotd_iNucf359viaigbjxyFhyaXA',
    appId: '1:300717101569:web:cd4b56fbbac97d5baa2600',
    messagingSenderId: '300717101569',
    projectId: 'iniciar-secion-2022',
    authDomain: 'iniciar-secion-2022.firebaseapp.com',
    storageBucket: 'iniciar-secion-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTxrAJ9-GWSi5-RgZXil8wD5gkQOsbEx0',
    appId: '1:300717101569:android:d123f12e0a085c69aa2600',
    messagingSenderId: '300717101569',
    projectId: 'iniciar-secion-2022',
    storageBucket: 'iniciar-secion-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCpHwBxhzp50IigErzivaH_6k3v6pI8wI',
    appId: '1:300717101569:ios:e43fe102c2a7f836aa2600',
    messagingSenderId: '300717101569',
    projectId: 'iniciar-secion-2022',
    storageBucket: 'iniciar-secion-2022.appspot.com',
    iosClientId: '300717101569-qkkqk55l5k0tdo69878ja2qv9h2qtgsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCpHwBxhzp50IigErzivaH_6k3v6pI8wI',
    appId: '1:300717101569:ios:e43fe102c2a7f836aa2600',
    messagingSenderId: '300717101569',
    projectId: 'iniciar-secion-2022',
    storageBucket: 'iniciar-secion-2022.appspot.com',
    iosClientId: '300717101569-qkkqk55l5k0tdo69878ja2qv9h2qtgsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUi',
  );
}
